
development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: devlp_db
  pool: 5
  host: localhost
  username: username
  password: pass


test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: test_db
  pool: 5
  host: localhost
  username: username
  password: pass